### ISSUE TITLE
Wooden Training weapon uses "Woody" not "Wood"

### ISSUE THREAD

**Issue by ZookTDribit** [Kriil/rimworld-combat-training#20]
https://github.com/Kriil/rimworld-combat-training/blob/master/Defs/ThingDefs_Misc/Weapons/MeleeTraining.xml

Line 23

Saddly I don't have any "Woody" to make this knife with XD

**Comment by Kriil** [comment]
C:\Program Files (x86)\Steam\steamapps\common\RimWorld\Data\Core\Defs\Misc\StuffCategoryDefs\StuffCatgories.xml

'woody' is a category of stuff that is wood-like.  It isn't a typo. There's also stony and leathery.  It simply  means that any type of wood like material can be used.

reference /Defs/ThingDefs_Misc/Weapons/MeleeMedieval.xml:  for usage by core game.
